Trust model and some semeval fixes
jedikarix/Gossips-spreading-simulator pull request #21
Opened 2019-05-30 22:54 UTC by lychanl

2019-05-31 19:12 UTC, k-checinski approved these changes

2019-06-01 10:00 UTC, saleph requested changes

2019-06-01 10:00 UTC, saleph commented on code/Simulation/Knowledge.py
> +                self.agents_trust[most_entailed.last_sender] += info_trust
Rozumiem, czemu nie użyłeś update_trust, ale powinieneś wykonać po tym self.trust_change_callback(most_entailed.last_sender, self.agents_trust[most_entailed.last_sender]) żeby graf nie stracił synchronizacji z aktualnymi zaufaniami

Całą metodę update_trust możesz wywalić

2019-06-01 10:00 UTC, saleph commented on code/Simulation/Knowledge.py
> +                self.agents_trust[most_entailed.last_sender] -= info_trust
jw. rzuć callback o zmianie

2019-06-02 12:10 UTC, lychanl commented on code/Simulation/Knowledge.py
> +                self.agents_trust[most_entailed.last_sender] += info_trust
fixed

2019-06-02 12:11 UTC, lychanl commented on code/Simulation/Knowledge.py
> +                self.agents_trust[most_entailed.last_sender] -= info_trust
fixed

2019-06-02 12:17 UTC, saleph approved these changes

2019-06-02 12:18 UTC, merged